In [1]:
#esto funciona igual que python utilizando terminal
print("hello world")

hello world


In [2]:
#funciones de operacion:
num1=int(input("Ingresa el numero 1:"))
num2=int(input("Ingresa el numero 2:"))
#suma
print("el resultado es",num1+num2)
#resta
print("el resultado es",num1-num2)
#multiplicacion
print("el resultado es",num1*num2)
#division
print("el resultado es",num1/num2)

el resultado es 3


In [3]:
#Estructuras de datos
lista=[]
for i in range(5):
    valor=input("ingrese los datos:")
    lista.append(valor)
print(lista)

['1', '2', '3', '4', '5']


In [19]:
#Mi primer dataframe
import pandas as pd

data = {'Marca': ['Adidas', 'Nike', 'Puma', 'Reebok', 'Under Armour'],
        'Precio': [50.00, 75.00, 45.00, 60.00, 55.00],
        'Cantidad': [100, 75, 67, 96, 69]}

df = pd.DataFrame(data)

df

Marca  Precio  Cantidad
0        Adidas    50.0       100
1          Nike    75.0        75
2          Puma    45.0        67
3        Reebok    60.0        96
4  Under Armour    55.0        69

In [20]:
#Agregar un nuevo registro
new_data = {'Marca': 'New Balance', 'Precio': 65.00, 'Cantidad': 100}

df.loc[len(df)]=new_data
df

Marca  Precio  Cantidad
0        Adidas    50.0       100
1          Nike    75.0        75
2          Puma    45.0        67
3        Reebok    60.0        96
4  Under Armour    55.0        69
5   New Balance    65.0       100

In [24]:
#renombrar columnas
df = df.rename(columns={'Marca': 'Marca de ropa', 'Precio': 'Precio en dólares'})
df

Marca de ropa  Precio en dólares  Cantidad
0        Adidas               50.0       100
2          Puma               45.0        67
4  Under Armour               55.0        69
5   New Balance               65.0       100

In [21]:
#identificar las dimensiones del dataframe
print(df.shape)


(6, 3)


In [22]:
#descriptivas basicas 
media_precios = df['Precio en dólares'].mean()
print('La media de los precios es:', media_precios)
precio_maximo = df['Precio en dólares'].max()
print('El precio máximo es:', precio_maximo)
precio_minimo = df['Precio en dólares'].min()
print('El precio mínimo es:', precio_minimo)


La media de los precios es: 58.333333333333336
El precio máximo es: 75.0
El precio mínimo es: 45.0


In [16]:
#eliminar registros
df = df.drop(2)
df

Marca de ropa  Precio en dólares  Cantidad
0        Adidas               50.0       100
3        Reebok               60.0        96
4  Under Armour               55.0        69
5   New Balance               65.0       100

In [22]:
#eliminar varios registros
df = df.drop([1, 3])
df

Marca  Precio  Cantidad
0        Adidas    50.0       100
2          Puma    45.0        67
4  Under Armour    55.0        69
5   New Balance    65.0       100

In [25]:
#Eliminar registros por condicion
df = df.drop(df.loc[df['Marca de ropa'] == 'Puma'].index)
df

Marca de ropa  Precio en dólares  Cantidad
0        Adidas               50.0       100
4  Under Armour               55.0        69
5   New Balance               65.0       100

In [26]:
#suma de una columna
suma_precios = df['Precio en dólares'].sum()
print('La suma de los precios es:', suma_precios)


La suma de los precios es: 170.0


In [27]:
df['Marca de ropa'] = df['Marca de ropa'].replace('Adidas', 'Nike')
print(df)


  Marca de ropa  Precio en dólares  Cantidad
0          Nike               50.0       100
4  Under Armour               55.0        69
5   New Balance               65.0       100


In [28]:
#Numpy
import numpy as np
# Array de una dimensión
a1 = np.array([1, 2, 3])
print(a1)


[1 2 3]


In [29]:
#visualizacion en dataframe
a11=pd.DataFrame(a1)
a11

0
0  1
1  2
2  3

In [57]:
# Array de dos dimensiones
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [58]:
#visualizacion en dataframe
a22=pd.DataFrame(a2)
a22

0  1  2
0  1  2  3
1  4  5  6

In [62]:
# Array de tres dimensiones
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [61]:
#visualizacion en dataframe
a3 = a3.reshape(-1, a3.shape[-1])
a33=pd.DataFrame(a3)
a33

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [63]:
#secuencia de array
a4 = np.arange(12, 120, 5)
print(a4)

[ 12  17  22  27  32  37  42  47  52  57  62  67  72  77  82  87  92  97
 102 107 112 117]


In [64]:
#acceso al array
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a[1, 0])

4


In [48]:
#otra forma de acceder
print(a[1][0])

4


In [49]:
#solamente las columnas 1 y 2
print(a[:, 0:2])

[[1 2]
 [4 5]]


In [44]:
#visualizacion en dataframe
aa=pd.DataFrame(a)
print(aa)

   0  1  2
0  1  2  3
1  4  5  6
